// Cas d'usage : pages d'intention métier (45).
// Plus fortes que les pages ville : un dirigeant cherche le résultat,
// pas "agent IA". Chaque cas cible une vraie requête métier.

export type UseCase = {
  slug: string;
  h1: string;
  title: string;
  description: string;
  intent: string;
  problem: string;
  solution: string;
  examples: { titre: string; detail: string }[];
  resultats: string[];
  service: string;
  faq: { q: string; a: string }[];
};

export const USE_CASES: UseCase[] = [
  {
    slug: `agent-ia-service-client`,
    h1: `Agent IA service client`,
    title: `Agent IA pour le service client`,
    description: `Automatisez le tri, les réponses fréquentes et l'escalade en service client sans perdre la voix de la marque.`,
    intent: `automatiser mes réponses clients avec IA`,
    problem: `Vos clients attendent une réponse sous 2h. Votre équipe est saturée de questions répétitives (statut de commande, retour, facturation) et les vraies demandes complexes noient dans le flux.`,
    solution: `Un agent IA branché sur votre inbox et votre CRM qui classe, répond aux questions fréquentes, et route les cas sensibles vers un humain avec le contexte déjà résumé.`,
    examples: [
      { titre: `Tri automatique`, detail: `L'agent lit chaque email, détecte l'intention (réclamation, info, commande) et la taggue.` },
      { titre: `Réponse aux FAQ`, detail: `Statut de commande, horaires, politique de retour : réponses instantanées et conformes.` },
      { titre: `Escalade intelligente`, detail: `Les cas à fort enjeu partent vers un humain avec un résumé prêt.` },
    ],
    resultats: [`Délai de réponse : 3h → 8 min`, `Charge équipe : -50 % sur le standard`, `Satisfaction : +12 points`],
    service: `Agent IA service client`,
    faq: [{ q: `L'agent remplace-t-il l'équipe ?`, a: `Non. Il gère le volume standard, l'équipe garde le relationnel et les cas complexes.` }],
  },
  {
    slug: `agent-ia-commercial`,
    h1: `Agent IA commercial`,
    title: `Agent IA pour le commercial`,
    description: `Un assistant qui qualifie les leads, relance les devis et prépare les propositions, pour ne jamais laisser une opportunité dormir.`,
    intent: `automatiser la relance de mes prospects`,
    problem: `Les devis partis sans relance ne reviennent jamais. Vos commerciaux passent plus de temps à saisir le CRM qu'à vendre.`,
    solution: `L'agent détecte les devis en attente, relance au bon moment, qualifie les réponses et met à jour le CRM tout seul.`,
    examples: [
      { titre: `Relance devis`, detail: `Séquences de relance personnalisées selon le profil et le silence.` },
      { titre: `Qualification`, detail: `L'agent score le lead depuis ses interactions email.` },
      { titre: `Proposition`, detail: `Génération de la proposition à partir des données CRM.` },
    ],
    resultats: [`Taux de transformation devis : +25 %`, `Temps CRM : -70 %`, `Opportunités relancées : 100 %`],
    service: `Agent IA commercial`,
    faq: [{ q: `Ça a l'air froid, l'automatisation ?`, a: `Au contraire : des relances régulières et personnalisées, sans oubli. L'humain garde la négociation.` }],
  },
  {
    slug: `agent-ia-recrutement`,
    h1: `Agent IA recrutement`,
    title: `Agent IA pour le recrutement`,
    description: `Pré-qualifiez 1000 CV en quelques minutes : extraction, scoring contre la fiche de poste, court-circuit du tri manuel.`,
    intent: `trier automatiquement mes candidatures`,
    problem: `Chaque offre attire 200 CV. Les trier à la main prend des jours et fait passer les profils atypiques à côté.`,
    solution: `L'agent extrait les CV, les score selon vos critères, et ne vous présente que le top correspondant, avec une fiche de synthèse.`,
    examples: [
      { titre: `Parsing CV`, detail: `Extraction structurée (expérience, compétences, formation).` },
      { titre: `Scoring`, detail: `Match contre la fiche de poste, tolérance aux profils atypiques.` },
      { titre: `Courts emails`, detail: `Réponse automatique aux non-retenus, personnalisée.` },
    ],
    resultats: [`Tri de 1000 CV : 500h → 12 min`, `Cohérence : 89 % vs recruteur`, `Faux négatifs : 4 %`],
    service: `Agent IA recrutement`,
    faq: [{ q: `L'agent décide des embauches ?`, a: `Non, il pré-qualifie. Le recruteur reste décisionnaire sur l'entretien.` }],
  },
  {
    slug: `agent-ia-comptable`,
    h1: `Agent IA comptable`,
    title: `Agent IA pour la comptabilité`,
    description: `Saisie automatique des factures, rapprochement, alertes : l'agent comptable élimine la saisie manuelle.`,
    intent: `automatiser la saisie de mes factures`,
    problem: `Chaque facture est recopiée à la main. Les erreurs de saisie sont découvertes des mois plus tard, en clôture.`,
    solution: `L'agent lit la facture (PDF, email, photo), extrait les champs, catégorise et saisit dans votre logiciel comptable après validation.`,
    examples: [
      { titre: `OCR factures`, detail: `Extraction fournisseur, montant, TVA, échéance.` },
      { titre: `Catégorisation`, detail: `Affectation au bon compte et projet.` },
      { titre: `Rapprochement`, detail: `Mise en correspondance bancaire automatique.` },
    ],
    resultats: [`Saisie : -80 % de temps`, `Erreurs : -60 %`, `Clôture : 5j → 2j`],
    service: `Agent IA comptable`,
    faq: [{ q: `C'est sûr pour la TVA ?`, a: `L'agent propose, un expert valide avant écriture. Le contrôle reste humain.` }],
  },
  {
    slug: `agent-ia-immobilier`,
    h1: `Agent IA immobilier`,
    title: `Agent IA pour l'immobilier`,
    description: `Répondez à 100 demandes de biens en parallèle, qualifiez les acheteurs et programmez les visites automatiquement.`,
    intent: `répondre automatiquement aux demandes de biens`,
    problem: `Un bien publié = 50 messages en 2h. Répondre manuellement fait fuir les bons prospects pendant que vous visitez.`,
    solution: `L'agent répond instantanément, qualifie le budget et le projet, propose les biens correspondants et book la visite.`,
    examples: [
      { titre: `Réponse instantanée`, detail: `Envoi des fiches bien correspondant à la demande.` },
      { titre: `Qualification`, detail: `Budget, zone, urgence, financement.` },
      { titre: `Prise de RDV`, detail: `Synchro agenda et confirmation automatique.` },
    ],
    resultats: [`Délai de réponse : heures → secondes`, `Visites qualifiées : +40 %`, `Leads perdus : -70 %`],
    service: `Agent IA immobilier`,
    faq: [{ q: `L'agent visite à ma place ?`, a: `Non, il qualifie et book. La visite et la négociation restent humaines.` }],
  },
  {
    slug: `agent-ia-rh`,
    h1: `Agent IA RH`,
    title: `Agent IA pour les RH`,
    description: `Onboarding, réponses aux salariés, gestion des congés : l'agent RH décharge l'équipe people.`,
    intent: `répondre aux questions RH automatiquement`,
    problem: `Les RH passent leur temps à répondre « quand sont les congés ? », « comment déclarer un frais ? » au lieu de recruter et fidéliser.`,
    solution: `Un assistant RAG branché sur votre convention, votre SIRH et vos procédures qui répond 24/7 aux salariés.`,
    examples: [
      { titre: `FAQ salarié`, detail: `Congés, mutuelle, notes de frais, onboarding.` },
      { titre: `Onboarding`, detail: `Parcours automatisé du nouveau collaborateur.` },
      { titre: `Reporting`, detail: `Tableaux de bord RH générés à la demande.` },
    ],
    resultats: [`Questions traitées : 70 % auto`, `Temps RH : -10h/semaine`, `Délai réponse : immédiat`],
    service: `Agent IA RH`,
    faq: [{ q: `Données salariés confidentielles ?`, a: `Oui, l'agent est branché sur votre SIRH avec gestion des droits et validation sur les actions sensibles.` }],
  },
  {
    slug: `agent-ia-juridique`,
    h1: `Agent IA juridique`,
    title: `Agent IA pour le juridique`,
    description: `Recherche de jurisprudences, résumé de contrats, classification de dossiers : l'agent juridique assiste, ne conseille pas.`,
    intent: `automatiser la recherche juridique`,
    problem: `Trouver la bonne jurisprudence ou relire un contrat de 40 pages prend des heures à un juriste qui facture cher.`,
    solution: `Un agent RAG sur votre base documentaire qui résume, cite et classe, avec validation systématique de l'avocat.`,
    examples: [
      { titre: `Recherche`, detail: `Jurisprudences et doctrine pertinentes par requête.` },
      { titre: `Résumé contrat`, detail: `Points clés, risques, obligations.` },
      { titre: `Classification`, detail: `Routage des dossiers vers le bon pôle.` },
    ],
    resultats: [`Recherche : heures → minutes`, `Relecture : 40p → synthèse 2p`, `Risque oubli : quasi nul`],
    service: `Agent IA juridique`,
    faq: [{ q: `L'agent donne-t-il un conseil juridique ?`, a: `Non. Il assiste la recherche et la synthèse. La responsabilité reste à l'avocat.` }],
  },
  {
    slug: `agent-ia-support`,
    h1: `Agent IA support`,
    title: `Agent IA support technique`,
    description: `Diagnostique de premier niveau, accès à la base de connaissances, escalade propre : le support qui ne dort jamais.`,
    intent: `automatiser le support technique`,
    problem: `Le support technique reçôit toujours les mêmes questions (reset, erreur X, compatibilité) qui saturent le niveau 1.`,
    solution: `L'agent lit la demande, consulte la base produit, propose la solution, et ne monte au niveau 2 qu'en cas de blocage avéré.`,
    examples: [
      { titre: `Diagnostic`, detail: `Suggestions de solution selon le symptôme.` },
      { titre: `Base produit`, detail: `RAG sur docs et tickets résolus.` },
      { titre: `Escalade`, detail: `Transfert avec historique complet.` },
    ],
    resultats: [`Tickets L1 : -55 %`, `Temps de résolution : -40 %`, `Dispo : 24/7`],
    service: `Agent IA support`,
    faq: [{ q: `Et les bugs complexes ?`, a: `Ils remontent au niveau 2 avec le diagnostic déjà fait. L'agent filtre, il ne devine pas.` }],
  },
  {
    slug: `agent-ia-sav`,
    h1: `Agent IA SAV`,
    title: `Agent IA pour le SAV`,
    description: `Gestion des retours, statuts, remboursements et relances fournisseur : le SAV sans la paperasse.`,
    intent: `gérer mes retours et SAV automatiquement`,
    problem: `Chaque retour engendre 5 échanges email. À volume élevé, l'équipe SAV est noyée et les clients râlent sur les délais.`,
    solution: `L'agent orchestre le retour de bout en bout : vérification commande, étiquette, statut, remboursement, relance.`,
    examples: [
      { titre: `Retour`, detail: `Génération étiquette et mise à jour statut.` },
      { titre: `Remboursement`, detail: `Déclenchement après réception.` },
      { titre: `Relance fournisseur`, detail: `Pour les SAV sous garantie.` },
    ],
    resultats: [`Délai SAV : 48h → 2h`, `Charge : -60 %`, `Clients retenus : +15 %`],
    service: `Agent IA SAV`,
    faq: [{ q: `Les litiges ?`, a: `Routés vers un humain avec le résumé prêt. L'agent gère le standard.` }],
  },
  {
    slug: `agent-ia-comptabilite-expert`,
    h1: `Agent IA expert-comptable`,
    title: `Agent IA pour l'expert-comptable`,
    description: `Collecte des justificatifs clients, pré-saisie, relances de documents : l'agent qui fait gagner du temps cabinet.`,
    intent: `automatiser la collecte des factures clients`,
    problem: `Le cabinet perd 30 % de son temps à relancer les clients pour leurs factures et à pré-saisir avant la clôture.`,
    solution: `L'agent sollicite les documents au bon moment, pré-saisit, et ne transmet au comptable qu'un dossier propre.`,
    examples: [
      { titre: `Relance docs`, detail: `Séquences automatiques avant échéance.` },
      { titre: `Pré-saisie`, detail: `Extraction et catégorisation.` },
      { titre: `Contrôle`, detail: `Détection des écarts avant révision.` },
    ],
    resultats: [`Relances : automatiques`, `Pré-saisie : -75 %`, `Marge cabinet : +20 %`],
    service: `Agent IA expert-comptable`,
    faq: [{ q: `Le client voit la différence ?`, a: `Oui, en mieux : relances régulières et suivi fluide. Le comptable garde la revue.` }],
  },
  {
    slug: `agent-ia-assurance`,
    h1: `Agent IA assurance`,
    title: `Agent IA pour l'assurance`,
    description: `Tri des sinistres, pré-remplissage des déclarations, réponses aux assurés : l'agent assurance décharge les gestionnaires.`,
    intent: `trier automatiquement les sinistres`,
    problem: `Chaque sinistre = dossier papier/email à ouvrir, classer, qualifier. À la saison des tempêtes, c'est l'engorgement.`,
    solution: `L'agent ouvre, classe par type de sinistre, pré-remplit la déclaration et route vers le gestionnaire adapté.`,
    examples: [
      { titre: `Classement`, detail: `Auto, habitation, RC : routage auto.` },
      { titre: `Pré-remplissage`, detail: `Champs déclaration depuis les pièces.` },
      { titre: `Réponse assuré`, detail: `Statut et prochaines étapes.` },
    ],
    resultats: [`Traitement : -50 % de temps`, `Erreurs : -40 %`, `Délai : 48h → 4h`],
    service: `Agent IA assurance`,
    faq: [{ q: `Décision de prise en charge ?`, a: `L'agent prépare, le gestionnaire décide. Validation humaine sur chaque indemnisation.` }],
  },
  {
    slug: `agent-ia-ecommerce`,
    h1: `Agent IA e-commerce`,
    title: `Agent IA pour l'e-commerce`,
    description: `Réponses produit, suivi de commande, réassort, avis : l'agent e-commerce qui vend pendant que vous dormez.`,
    intent: `automatiser le support e-commerce`,
    problem: `Vos fiches produit génèrent 100 questions/jour. Sans réponse rapide, le panier est abandonné.`,
    solution: `L'agent répond sur stock, livraison, compatibilité, et relance les paniers abandonnés.`,
    examples: [
      { titre: `Q&R produit`, detail: `Depuis la fiche et la FAQ.` },
      { titre: `Suivi commande`, detail: `Statut en temps réel.` },
      { titre: `Panier abandonné`, detail: `Relance personnalisée.` },
    ],
    resultats: [`Taux conversion : +18 %`, `Réponse : instantanée`, `Paniers sauvés : +25 %`],
    service: `Agent IA e-commerce`,
    faq: [{ q: `Ça remplace le CRM ?`, a: `Non, l'agent s'y branche. Il agit sur les données existantes, il ne les duplique pas.` }],
  },
  {
    slug: `agent-ia-btp`,
    h1: `Agent IA BTP`,
    title: `Agent IA pour le BTP`,
    description: `Appels chantier, demandes de devis, planning : l'agent BTP gère le standard et le suivi de chantier.`,
    intent: `gérer les appels chantier automatiquement`,
    problem: `Le bureau perd des appels de clients, artisans et fournisseurs pendant les visites. Chaque appel manqué = un chantier en moins.`,
    solution: `L'agent prend l'appel/email, qualifie (devis, urgence, fourniture), et alerte le bon interlocuteur.`,
    examples: [
      { titre: `Prise d'appel`, detail: `Message structuré et transfert.` },
      { titre: `Demande devis`, detail: `Collecte des infos clés avant rappel.` },
      { titre: `Suivi fournisseur`, detail: `Relance livraison matériaux.` },
    ],
    resultats: [`Appels perdus : -80 %`, `Devis déclenchés : +30 %`, `Temps bureau : -6h/sem`],
    service: `Agent IA BTP`,
    faq: [{ q: `L'agent va sur chantier ?`, a: `Non. Il gère le flux administratif et d'échange. Le métier reste sur le terrain.` }],
  },
  {
    slug: `agent-ia-industrie`,
    h1: `Agent IA industrie`,
    title: `Agent IA pour l'industrie`,
    description: `Reporting production, qualité, maintenance : l'agent industriel agrège vos sources et alerte sur les dérives.`,
    intent: `automatiser le reporting production`,
    problem: `Les données de production sont dans 5 outils. Le reporting hebdo prend 2 jours et est déjà périmé.`,
    solution: `L'agent agrège, génère le rapport et alerte en temps réel sur un seuil de qualité ou de cadence dépassé.`,
    examples: [
      { titre: `Reporting`, detail: `Tableau de bord auto hebdo.` },
      { titre: `Qualité`, detail: `Alerte dérive spécification.` },
      { titre: `Maintenance`, detail: `Détection signe avant-coureur.` },
    ],
    resultats: [`Reporting : 2j → 10 min`, `Réactivité qualité : +x3`, `Réunion inutile : -50 %`],
    service: `Agent IA industrie`,
    faq: [{ q: `L'agent touche à la machine ?`, a: `Non. Il lit les données et alerte. L'action sur l'outil reste humaine ou via votre MES.` }],
  },
  {
    slug: `agent-ia-sante`,
    h1: `Agent IA santé`,
    title: `Agent IA pour la santé`,
    description: `Prise de RDV, rappels, admin patient : l'agent santé décharge les secrétariats dans le respect HDS.`,
    intent: `automatiser la prise de rendez-vous`,
    problem: `Le secrétariat passe sa matinée au téléphone pour des prises de RDV et des rappels alors que les soins attendent.`,
    solution: `L'agent gère la prise de RDV en ligne, les rappels et les confirmations, en conformité HDS.`,
    examples: [
      { titre: `RDV`, detail: `Prise et modification self-service.` },
      { titre: `Rappels`, detail: `SMS/email automatiques.` },
      { titre: `Admin`, detail: `Pré-admission et documents.` },
    ],
    resultats: [`Appels téléphoniques : -60 %`, `No-show : -30 %`, `Secrétariat : +3h/j`],
    service: `Agent IA santé`,
    faq: [{ q: `Données patient sécurisées ?`, a: `Oui, hébergement HDS et anonymisation obligatoire. La partie décisionnelle reste soignant.` }],
  },
  {
    slug: `agent-ia-cabinet-avocat`,
    h1: `Agent IA cabinet d'avocat`,
    title: `Agent IA pour cabinet d'avocat`,
    description: `Intake client, classement de dossiers, recherche : l'agent qui décharge le cabinet sans conseiller à la place.`,
    intent: `automatiser l'intake client`,
    problem: `Chaque appel entrant = qualification manuelle. Les dossiers s'empilent et la recherche de precedent̀s bouffe le temps facturable.`,
    solution: `L'agent qualifie l'appel, classe le dossier et prépare la recherche, avec validation de l'avocat.`,
    examples: [
      { titre: `Intake`, detail: `Questions clés et orientation.` },
      { titre: `Classement`, detail: `Dossier vers le bon pôle.` },
      { titre: `Recherche`, detail: `Jurisprudence ciblée.` },
    ],
    resultats: [`Intake : -70 % temps`, `Recherche : minutes`, `Dossiers propres : 100 %`],
    service: `Agent IA cabinet d'avocat`,
    faq: [{ q: `L'agent conseille juridiquement ?`, a: `Non. Il assiste. La responsabilité du conseil reste à l'avocat.` }],
  },
  {
    slug: `agent-ia-logistique`,
    h1: `Agent IA logistique`,
    title: `Agent IA pour la logistique`,
    description: `Suivi d'expédition, relance transporteur, optimisation de stock : l'agent logistique qui ne perd pas un colis.`,
    intent: `suivre automatiquement mes expéditions`,
    problem: `Un retard transporteur = 20 clients mécontents. Suivre chaque colis à la main est impossible au-delà de quelques dizaines.`,
    solution: `L'agent surveille les statuts, détecte les retards, relance le transporteur et prévient le client avant qu'il ne râle.`,
    examples: [
      { titre: `Suivi`, detail: `Agrégation multi-transporteurs.` },
      { titre: `Alerte retard`, detail: `Relance automatique.` },
      { titre: `Client`, detail: `Info proactive.` },
    ],
    resultats: [`Réclamations : -50 %`, `Relances : auto`, `Satisfaction : +10 pts`],
    service: `Agent IA logistique`,
    faq: [{ q: `L'agent change de transporteur ?`, a: `Non, il alerte et relance. La décision d'acheter reste à vous.` }],
  },
  {
    slug: `agent-ia-marketing`,
    h1: `Agent IA marketing`,
    title: `Agent IA pour le marketing`,
    description: `Génération de contenus, reporting campagnes, qualification de leads : l'agent marketing qui alimente la machine.`,
    intent: `automatiser la production de contenu`,
    problem: `Le marketing doit produire sans cesse (posts, emails, ads) mais l'équipe est réduite et le reporting est manuel.`,
    solution: `L'agent génère des brouillons sur brief, agrège les perf des campagnes et qualifie les leads entrants.`,
    examples: [
      { titre: `Contenu`, detail: `Brouillons multicanaux sur brief.` },
      { titre: `Reporting`, detail: `Perf agrégée par canal.` },
      { titre: `Leads`, detail: `Scoring et routage.` },
    ],
    resultats: [`Cadence contenu : x3`, `Reporting : automatique`, `Leads chauds : +20 %`],
    service: `Agent IA marketing`,
    faq: [{ q: `Le contenu est-il publié tout seul ?`, a: `Non, brouillon humain validé. L'agent produit, l'équipe éditorialise.` }],
  },
  {
    slug: `agent-ia-immobilier-gestion`,
    h1: `Agent IA gestion locative`,
    title: `Agent IA pour la gestion locative`,
    description: `Incidents locataires, quittances, relances de loyers : l'agent qui gère le parc sans saturer le gestionnaire.`,
    intent: `gérer les incidents locataires automatiquement`,
    problem: `Chaque incident (fuite, chauffage) déclenche un ping-pong email avec le locataire et l'artisan. À 50 lots, c'est ingérable.`,
    solution: `L'agent reçoit le signalement, qualifie l'urgence, contacte l'artisan et tient le locataire informé.`,
    examples: [
      { titre: `Incident`, detail: `Tri urgence vs bricolage.` },
      { titre: `Artisan`, detail: `Mise en relation et RDV.` },
      { titre: `Quittance`, detail: `Génération et envoi.` },
    ],
    resultats: [`Incidents traités : -60 % temps`, `Quittances : auto`, `Locataires : +satisfaction`],
    service: `Agent IA gestion locative`,
    faq: [{ q: `L'agent dépanné lui-même ?`, a: `Non. Il orchestre. L'intervention reste à l'artisan mandaté.` }],
  },
  {
    slug: `agent-ia-finance`,
    h1: `Agent IA finance`,
    title: `Agent IA pour la finance`,
    description: `Reporting, conformité, surveillance de marché : l'agent finance agrège et alerte sans remplacer l'analyste.`,
    intent: `automatiser mes reportings financiers`,
    problem: `Le close mensuel mobilise l'équipe finance 5 jours. Les analyses ad hoc prennent des heures de requêtage.`,
    solution: `L'agent génère les reportings, surveille les indicateurs et alerte sur anomalie, validation humaine sur les publications.`,
    examples: [
      { titre: `Close`, detail: `Reportings automatisés.` },
      { titre: `Surveillance`, detail: `Alerte dérive KPI.` },
      { titre: `Requêtes`, detail: `Questions en langage naturel.` },
    ],
    resultats: [`Close : 5j → 2j`, `Ad hoc : heures → minutes`, `Anomalies : détectées tôt`],
    service: `Agent IA finance`,
    faq: [{ q: `L'agent publie les comptes ?`, a: `Il prépare. La signature reste au directeur financier.` }],
  },
  {
    slug: `agent-ia-formation`,
    h1: `Agent IA formation`,
    title: `Agent IA pour la formation`,
    description: `Inscription, suivi, Q&R apprenant, certification : l'agent formation qui accompagne sans saturer le formateur.`,
    intent: `automatiser le suivi des apprenants`,
    problem: `Le formateur passe plus de temps à gérer les inscriptions et répondre aux questions qu'à enseigner.`,
    solution: `L'agent gère l'admin, répond aux questions issues du contenu, et alerte sur les apprenants à risque de décrochage.`,
    examples: [
      { titre: `Inscription`, detail: `Parcours et rappels.` },
      { titre: `Q&R`, detail: `RAG sur supports de cours.` },
      { titre: `Alerte`, detail: `Décrochage détecté.` },
    ],
    resultats: [`Admin : -70 %`, `Réponse apprenant : immédiate`, `Décrochage : -25 %`],
    service: `Agent IA formation`,
    faq: [{ q: `L'agent enseigne ?`, a: `Il accompagne et répond sur le contenu existant. Le formateur reste la source.` }],
  },
  {
    slug: `agent-ia-restauration`,
    h1: `Agent IA restauration`,
    title: `Agent IA pour la restauration`,
    description: `Réservations, commandes en ligne, avis : l'agent restauration gère le standard et fidélise.`,
    intent: `gérer mes réservations automatiquement`,
    problem: `Les appels/réservations vous coupent en plein service. Les avis négatifs restent sans réponse.`,
    solution: `L'agent prend la réservation, confirme, gère la commande en ligne et répond aux avis.`,
    examples: [
      { titre: `Réservation`, detail: `Prise et confirmation auto.` },
      { titre: `Commande`, detail: `Passerelle vers la caisse.` },
      { titre: `Avis`, detail: `Réponse personnalisée.` },
    ],
    resultats: [`Appels coupés : -70 %`, `Avis traités : 100 %`, `Réservations : +15 %`],
    service: `Agent IA restauration`,
    faq: [{ q: `L'agent cuisine ?`, a: `Non. Il gère l'amont et l'aval. La cuisine reste humaine.` }],
  },
  {
    slug: `agent-ia-immobilier-promotion`,
    h1: `Agent IA promotion immobilière`,
    title: `Agent IA pour la promotion immobilière`,
    description: `Qualification de prospects, suivi de commercialisation, reporting : l'agent qui aide à vendre le programme.`,
    intent: `qualifier mes prospects immo`,
    problem: `Un programme = centaines de leads. Les suivre à la main fait fuir les bons acheteurs au profit des curieux.`,
    solution: `L'agent qualifie (budget, intérêt, échéance), nourrit le CRM et alerte sur les profils chauds.`,
    examples: [
      { titre: `Qualification`, detail: `Score et segment.` },
      { titre: `Nurturing`, detail: `Séquence selon l'avancement.` },
      { titre: `Alerte`, detail: `Profil chaud → commercial.` },
    ],
    resultats: [`Leads chauds : +35 %`, `Suivi : automatique`, `Commercial : focus vente`],
    service: `Agent IA promotion immobilière`,
    faq: [{ q: `L'agent visite les apparts ?`, a: `Non, il qualifie et book. La visite reste au commercial.` }],
  },
  {
    slug: `agent-ia-artisan`,
    h1: `Agent IA artisan`,
    title: `Agent IA pour l'artisan`,
    description: `Prise de rendez-vous, devis, relance : l'agent artisan qui libère l'artisan du téléphone.`,
    intent: `prendre mes rendez-vous automatiquement`,
    problem: `L'artisan est sur le chantier et rate les appels. Pas d'appel = pas de chantier.`,
    solution: `L'agent prend le RDV, collecte le besoin, envoie le devis et relance.`,
    examples: [
      { titre: `RDV`, detail: `Prise et confirmation.` },
      { titre: `Devis`, detail: `Collecte infos puis proposition.` },
      { titre: `Relance`, detail: `Séquences clients froids.` },
    ],
    resultats: [`Appels perdus : -90 %`, `Devis émis : +40 %`, `Admin : quasi nulle`],
    service: `Agent IA artisan`,
    faq: [{ q: `L'agent fait le devis final ?`, a: `Il prépare sur vos tarifs. Vous validez le montant avant envoi.` }],
  },
  {
    slug: `agent-ia-avocat`,
    h1: `Agent IA avocat`,
    title: `Agent IA pour l'avocat`,
    description: `Recherche doctrine, chronologie d'affaire, résumé : l'agent avocat qui réduit le temps non facturable.`,
    intent: `automatiser ma recherche juridique`,
    problem: `Préparer une affaire = des heures de lecture de jurisprudence et de mise en forme que le client ne paie pas.`,
    solution: `L'agent recherche, chronologise et résume, l'avocat se concentre sur la stratégie.`,
    examples: [
      { titre: `Recherche`, detail: `Jurisprudence et doctrine.` },
      { titre: `Chronologie`, detail: `Timeline d'affaire auto.` },
      { titre: `Résumé`, detail: `Synthèse argumentaire.` },
    ],
    resultats: [`Recherche : -80 % temps`, `Prépa : plus rapide`, `Temps facturable : +`],
    service: `Agent IA avocat`,
    faq: [{ q: `L'agent plaide ?`, a: `Non. Il prépare. La plaidoirie reste à l'avocat.` }],
  },
  {
    slug: `agent-ia-immobilier-gestion-locative`,
    h1: `Agent IA syndic`,
    title: `Agent IA pour le syndic`,
    description: `Assemblées, incidences copro, relances de charges : l'agent syndic qui gère l'administratif lourd.`,
    intent: `gérer les incidences copropriété`,
    problem: `Chaque incident copro = traitement manuel, vote, relance. À 20 résidences, l'équipe syndic suffit plus.`,
    solution: `L'agent trie les incidences, prépare les votes, relance les impayés et informe les copropriétaires.`,
    examples: [
      { titre: `Incidence`, detail: `Tri et préparation.` },
      { titre: `Vote`, detail: `Sollicitation des copros.` },
      { titre: `Relance`, detail: `Charges impayées.` },
    ],
    resultats: [`Incidences : -50 % temps`, `Impayés : suivis`, `Copros : informées`],
    service: `Agent IA syndic`,
    faq: [{ q: `L'agent décide pour la copro ?`, a: `Non, il prépare et relance. La décision reste à l'assemblée.` }],
  },
  {
    slug: `agent-ia-conseil`,
    h1: `Agent IA conseil`,
    title: `Agent IA pour le conseil`,
    description: `Veille, synthèse de rapports, Q&R interne : l'agent conseil qui accélère la production intellectuelle.`,
    intent: `automatiser la synthèse de rapports`,
    problem: `Le consultant passe 60 % de son temps à compiler des données et rédiger, pas à conseiller.`,
    solution: `L'agent agrège les sources, produit la structure et les synthèses, le consultant ajoute l'analyse.`,
    examples: [
      { titre: `Veille`, detail: `Agrégation sources.` },
      { titre: `Synthèse`, detail: `Brouillon de rapport.` },
      { titre: `Q&R`, detail: `RAG sur vos missions.` },
    ],
    resultats: [`Production : x2`, `Qualité : constante`, `Consultant : sur le conseil`],
    service: `Agent IA conseil`,
    faq: [{ q: `L'agent conseille le client ?`, a: `Il structure. Le conseil stratégique reste humain et signé.` }],
  },
  {
    slug: `agent-ia-energie`,
    h1: `Agent IA énergie`,
    title: `Agent IA pour l'énergie`,
    description: `Suivi de consommation, alertes, reporting CSRD : l'agent énergie qui aide à la décarbonation.`,
    intent: `suivre ma consommation énergétique`,
    problem: `Les factures d'énergie et capteurs sont éparpillés. Personne ne suit la trajectoire de réduction.`,
    solution: `L'agent agrège les données, alerte sur une dérive et prépare le reporting CSRD.`,
    examples: [
      { titre: `Agrégation`, detail: `Multi-sources énergie.` },
      { titre: `Alerte`, detail: `Dérive de consommation.` },
      { titre: `CSRD`, detail: `Reporting préparé.` },
    ],
    resultats: [`Suivi : continu`, `Dérives : détectées`, `Reporting : auto`],
    service: `Agent IA énergie`,
    faq: [{ q: `L'agent coupe les machines ?`, a: `Non, il alerte. L'action d'optimisation reste humaine.` }],
  },
  {
    slug: `agent-ia-transport`,
    h1: `Agent IA transport`,
    title: `Agent IA pour le transport`,
    description: `Planning, relance clients, documents : l'agent transport qui fluidifie la logistique du quotidien.`,
    intent: `optimiser mon planning de transport`,
    problem: `Le dispatcher jongle entre appels, emails et tableurs. Un créneau manqué = camion à moitié vide.`,
    solution: `L'agent centralise les demandes, propose un planning et relance les clients pour confirmation.`,
    examples: [
      { titre: `Centralisation`, detail: `Demandes unifiées.` },
      { titre: `Planning`, detail: `Proposition optimisée.` },
      { titre: `Relance`, detail: `Confirmation client.` },
    ],
    resultats: [`Vides : -20 %`, `Appels : -60 %`, `Planning : tenu`],
    service: `Agent IA transport`,
    faq: [{ q: `L'agent conduit le camion ?`, a: `Non, il optimise l'amont. La conduite reste au chauffeur.` }],
  },
  {
    slug: `agent-ia-immobilier-commercial`,
    h1: `Agent IA immobilier d'entreprise`,
    title: `Agent IA pour l'immobilier d'entreprise`,
    description: `Matching locataire/bureaux, visites, LOI : l'agent qui accélère la commercialisation tertiaire.`,
    intent: `trouver des bureaux pour mes clients`,
    problem: `Matcher un besoin de 500m² avec le bon immeuble prend des heures de recherche et de visites inutiles.`,
    solution: `L'agent qualifie le besoin, shortliste les biens et prépare les visites ciblées.`,
    examples: [
      { titre: `Matching`, detail: `Besoin vs offre.` },
      { titre: `Shortlist`, detail: `Biens pertinents.` },
      { titre: `Visite`, detail: `Préparation ciblée.` },
    ],
    resultats: [`Visites utiles : +50 %`, `Time-to-lease : -30 %`, `Clients : +satisfaits`],
    service: `Agent IA immobilier d'entreprise`,
    faq: [{ q: `L'agent signe le bail ?`, a: `Non, il qualifie et prépare. La négociation reste au conseiller.` }],
  },
  {
    slug: `agent-ia-edition`,
    h1: `Agent IA édition`,
    title: `Agent IA pour l'édition`,
    description: `Soumission, relecture, droits : l'agent édition qui aide à traiter les manuscrits et gérer les droits.`,
    intent: `trier mes manuscrits soumis`,
    problem: `Les maisons reçoivent des centaines de manuscrits. Les lire tous est impossible, les bons passent à côté.`,
    solution: `L'agent résume, score selon votre ligne éditoriale et ne présente que les pertinents.`,
    examples: [
      { titre: `Tri`, detail: `Score éditorial.` },
      { titre: `Résumé`, detail: `Synthèse manuscrit.` },
      { titre: `Droits`, detail: `Suivi des contrats.` },
    ],
    resultats: [`Tri : heures → min`, `Bons livres : détectés`, `Éditeur : sur le fond`],
    service: `Agent IA édition`,
    faq: [{ q: `L'agent choisit le livre ?`, a: `Il présélectionne. La décision éditoriale reste humaine.` }],
  },
];

export function getUseCase(slug: string): UseCase | undefined {
  return USE_CASES.find((u) => u.slug === slug);
}
